[build]
  command = "npm run export"
  functions = "lambda"
  publish = "__sapper__/export"
  base = "/"

[functions]
  directory = "functions"

[build]
  ignore = "git diff -quiet HEAD^ HEAD sub_dir/"
